//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BinMonitor.Common.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class AdminOverride : global::System.Configuration.ApplicationSettingsBase {
        
        private static AdminOverride defaultInstance = ((AdminOverride)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AdminOverride())));
        
        public static AdminOverride Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A8172E545D68C0FB9D1B355F45A28CFD")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
        }
    }
}
