//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanquire.Public.Properties
{
	
	
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("ICSharpCode.SettingsEditor.SettingsCodeGeneratorTool", "4.2.2.8818")]
	internal sealed partial class Encryption : global::System.Configuration.ApplicationSettingsBase
	{
		
		private static Encryption defaultInstance = ((Encryption)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Encryption())));
		
		public static Encryption Default
		{
			get
			{
				return defaultInstance;
			}
		}
		
		[global::System.Configuration.ApplicationScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("RURPQ1M=")]
		public string ProtectedDataEntropy
		{
			get
			{
				return ((string)(this["ProtectedDataEntropy"]));
			}
		}
	}
}
