//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanquire.Public.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class SQArchiverSelector : global::System.Configuration.ApplicationSettingsBase {
        
        private static SQArchiverSelector defaultInstance = ((SQArchiverSelector)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SQArchiverSelector())));
        
        public static SQArchiverSelector Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PreviousSelectedArchiverName {
            get {
                return ((string)(this["PreviousSelectedArchiverName"]));
            }
            set {
                this["PreviousSelectedArchiverName"] = value;
            }
        }
    }
}
