//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanquire.Public.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    public sealed partial class SQImageRevision : global::System.Configuration.ApplicationSettingsBase {
        
        private static SQImageRevision defaultInstance = ((SQImageRevision)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SQImageRevision())));
        
        public static SQImageRevision Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GeneratePreviewImage {
            get {
                return ((bool)(this["GeneratePreviewImage"]));
            }
            set {
                this["GeneratePreviewImage"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1440, 920")]
        public global::System.Drawing.Size MaxPreviewImageSize {
            get {
                return ((global::System.Drawing.Size)(this["MaxPreviewImageSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("256, 256")]
        public global::System.Drawing.Size MaxThumbnailImageSize {
            get {
                return ((global::System.Drawing.Size)(this["MaxThumbnailImageSize"]));
            }
        }
    }
}
