//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanquire.Public.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    public sealed partial class SQTwain : global::System.Configuration.ApplicationSettingsBase {
        
        private static SQTwain defaultInstance = ((SQTwain)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SQTwain())));
        
        public static SQTwain Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PreviousDataSourceName {
            get {
                return ((string)(this["PreviousDataSourceName"]));
            }
            set {
                this["PreviousDataSourceName"] = value;
            }
        }
    }
}
