//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanQuireSqlCmds.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DanCRoper")]
        public string SqlSever {
            get {
                return ((string)(this["SqlSever"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ScanquireUsers")]
        public string SqlDataBase {
            get {
                return ((string)(this["SqlDataBase"]));
            }
            set {
                this["SqlDataBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAFFcQ2jDA8ECcIGnDAE4cqgAAAAACAAAAAAAQZgAAAAEAACAAAABOeHfrkko9G+/oHRpi9T6bSjYgd+U6cAT7zujl3jjQ9AAAAAAOgAAAAAIAACAAAACEsNmYQ9kA/JG7EIFg0qKSeamvxSNKqp3edJDCjuFQKyAAAABfzU4uPMgDQSniqYEyvuTY4UoJKylg93UlNC8PFW2k+kAAAAAVEQ5vt6BH7kgFmFKbtp25i5K10aW1+aC3ZF14aZQTfYdXbv8CrpKSFbGwCaX6dcWuKiZpdY8j+B0sqoQmKSDx")]
        public string DbUserName {
            get {
                return ((string)(this["DbUserName"]));
            }
            set {
                this["DbUserName"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eDoButTeMt59701=")]
        public string DbKey {
            get {
                return ((string)(this["DbKey"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAFFcQ2jDA8ECcIGnDAE4cqgAAAAACAAAAAAAQZgAAAAEAACAAAADeliDK7w4wja6rNdnzLaid3mQlOxQ7OZCD+dXUhPTWSgAAAAAOgAAAAAIAACAAAACzdg9VNZnWsgkB4HYumvgfQqk1vXwFSMG8CZPdhgW0/iAAAACuTfRbiWNJHA1y+qhFBznlvfePsEj2k+h9RD0LaWFnVkAAAAAnSSS/p8XPTN3IuinsmjUNC19W/GMmOolikDv+kZGeLIug4iugnnUPWyBxMUhlUIMwl/42nhjs0Xmprro6P06c")]
        public string DbPassWord {
            get {
                return ((string)(this["DbPassWord"]));
            }
            set {
                this["DbPassWord"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int SqlServerTimeOut {
            get {
                return ((int)(this["SqlServerTimeOut"]));
            }
        }
    }
}
