//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanquire.Public.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    public sealed partial class SQImageListViewer : global::System.Configuration.ApplicationSettingsBase {
        
        private static SQImageListViewer defaultInstance = ((SQImageListViewer)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SQImageListViewer())));
        
        public static SQImageListViewer Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control")]
        public global::System.Drawing.Color DefaultCheckedItemBorderColor {
            get {
                return ((global::System.Drawing.Color)(this["DefaultCheckedItemBorderColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DefaultImageCheckedState {
            get {
                return ((bool)(this["DefaultImageCheckedState"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int DefaultItemBorderWidth {
            get {
                return ((int)(this["DefaultItemBorderWidth"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int DefaultItemMarginWidth {
            get {
                return ((int)(this["DefaultItemMarginWidth"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 330")]
        public global::System.Drawing.Size DefaultLargeThumbnailSize {
            get {
                return ((global::System.Drawing.Size)(this["DefaultLargeThumbnailSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("85, 110")]
        public global::System.Drawing.Size DefaultSmallThumbnailSize {
            get {
                return ((global::System.Drawing.Size)(this["DefaultSmallThumbnailSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkRed")]
        public global::System.Drawing.Color DefaultUnCheckedItemBorderColor {
            get {
                return ((global::System.Drawing.Color)(this["DefaultUnCheckedItemBorderColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("170, 220")]
        public global::System.Drawing.Size DefaultMediumThumbnailSize {
            get {
                return ((global::System.Drawing.Size)(this["DefaultMediumThumbnailSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color DefaultSelectedThumbnailBorderColor {
            get {
                return ((global::System.Drawing.Color)(this["DefaultSelectedThumbnailBorderColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ThumbnailMargin {
            get {
                return ((int)(this["ThumbnailMargin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ThumbnailBorder {
            get {
                return ((int)(this["ThumbnailBorder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float DefaultDeskewAngle {
            get {
                return ((float)(this["DefaultDeskewAngle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int DefaultSplitterDistance {
            get {
                return ((int)(this["DefaultSplitterDistance"]));
            }
        }
    }
}
