//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanquire.Public.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    public sealed partial class SQFilesystemArchiver : global::System.Configuration.ApplicationSettingsBase {
        
        private static SQFilesystemArchiver defaultInstance = ((SQFilesystemArchiver)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SQFilesystemArchiver())));
        
        public static SQFilesystemArchiver Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultRootPath {
            get {
                return ((string)(this["DefaultRootPath"]));
            }
        }
    }
}
