//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edocs.Libaray.Upload.Archive.Batches.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\Archives\\MDTBackUp\\")]
        public string ArchivesFolder {
            get {
                return ((string)(this["ArchivesFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:5555/api/")]
        public string EdocsWebApi {
            get {
                return ((string)(this["EdocsWebApi"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeleteBatchOnSuccess {
            get {
                return ((bool)(this["DeleteBatchOnSuccess"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Call e-Docs USA support @(406)-565-3465 and tell them batchid:{bid}for BSB Plan d" +
            "id not upload.")]
        public string EdocsSupport {
            get {
                return ((string)(this["EdocsSupport"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\Archives\\JsonFilesBackup\\")]
        public string JsonFilesBackUpFolder {
            get {
                return ((string)(this["JsonFilesBackUpFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MakeCopyUploadImage {
            get {
                return ((bool)(this["MakeCopyUploadImage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\Archives\\MDTBackupPDF\\")]
        public string UploadedImagesCopyFolder {
            get {
                return ((string)(this["UploadedImagesCopyFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int DaysToKeepCopyFolder {
            get {
                return ((int)(this["DaysToKeepCopyFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{ApplicationDir}\\Local\\EdocsArchiverUploadLogs\\")]
        public string LogFolder {
            get {
                return ((string)(this["LogFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int DaysToKeepLogFiles {
            get {
                return ((int)(this["DaysToKeepLogFiles"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LoopRetryUpLoad {
            get {
                return ((int)(this["LoopRetryUpLoad"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ThreadSleep {
            get {
                return ((int)(this["ThreadSleep"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int LoopNotifyUser {
            get {
                return ((int)(this["LoopNotifyUser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SendEmailErrorsOnly {
            get {
                return ((bool)(this["SendEmailErrorsOnly"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ThreadSleepSeconds {
            get {
                return ((int)(this["ThreadSleepSeconds"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\Archives\\MDTBackupOverWrite\\")]
        public string OverWriteFolder {
            get {
                return ((string)(this["OverWriteFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OverWriteEmailCC {
            get {
                return ((string)(this["OverWriteEmailCC"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Archives\\Edocs.OCR.Searchable.PDF\\Edocs.Ocr.Searchable.Pdf.exe")]
        public string OCRExe {
            get {
                return ((string)(this["OCRExe"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OCRP8398898A")]
        public string OCRApiKey {
            get {
                return ((string)(this["OCRApiKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://apipro1.ocr.space/parse/image")]
        public string OCRWebApi {
            get {
                return ((string)(this["OCRWebApi"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OCRISTable {
            get {
                return ((bool)(this["OCRISTable"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Edocs.Icr.Ocr.Google\\")]
        public string LCROCRExe {
            get {
                return ((string)(this["LCROCRExe"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XNvT1ZL9JwsPLtI/AXGu8pJ7aGtkcaU5GoF6ibbzJ0RTuU5reUqdquOqJEyohAeNFZDjoAxM/tEVQNyR1" +
            "g5kCg==")]
        public string AzureBlobAccountKey {
            get {
                return ((string)(this["AzureBlobAccountKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DefaultEndpointsProtocol=https;AccountName=edocsnypstorageprod;AccountKey=XNvT1ZL" +
            "9JwsPLtI/AXGu8pJ7aGtkcaU5GoF6ibbzJ0RTuU5reUqdquOqJEyohAeNFZDjoAxM/tEVQNyR1g5kCg=" +
            "=;EndpointSuffix=core.windows.net")]
        public string AzureBlobStorageConnectionString {
            get {
                return ((string)(this["AzureBlobStorageConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("edocsnypstorageprod/doh")]
        public string AzureContainer {
            get {
                return ((string)(this["AzureContainer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Google_LCROCR\\Diocese_Of_Helena\\LCROCR")]
        public string LCROCROutPutFolder {
            get {
                return ((string)(this["LCROCROutPutFolder"]));
            }
        }
    }
}
