using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
// EmojiTags.cs https://www.mastertemplate.co.uk/emoji-entities-hexcode.php
//https://html-color.codes/red
namespace BMRMobileApp.Utilites
{
    
    public class EmojiTags
    {
        public const string DefaultTagColor = "#D3D3D3";
        public const string Happy = "😊";
        public const string Sad = "😢";
        public const string Frustrated = "😠";
        public const string Calm = "😌";
        public const string Neutral = "😶";
        public const string Confused = "😕";
        public const string Excited = "🤩";
        public const string Anxious = "😰";
        public const string Bored = "😐";
        public const string Tired = "😴";
        public const string Stressed = "😖";
        public const string Lonely = "😔";
        public const string Hopeful = "🤞";
        public const string Grateful = "🙏";
        public const string Proud = "😌";
        public const string Relaxed = "😌";
        public const string Energetic = "⚡";
        public const string Playful = "😜";
        public const string Focused = "🎯";
        public const string Loved = "❤️";
        public const string Inspired = "🌟";
        public const string Motivated = "🚀";
        public const string Peaceful = "☮️";
        public const string Determined = "💪";
        public const string Curious = "🤔";
        public const string Amused = "😄";
        public const string Confident = "😎";
        public const string Shocked = "😲";
        public const string Disappointed = "😞";
        public const string Embarrassed = "😳";
        public const string Guilty = "😔";
        public const string Jealous = "😒";
        public const string Nostalgic = "🕰️";
        public const string Relieved = "😌";
        public const string GratefulFace = "😊";
        public const string SmilingFaceWithHearts = "🥰";
        public const string FaceWithTearsOfJoy = "😂";
        public const string FaceBlowingAKiss = "😘";

        public const string SmilingFaceWithSunglasses = "😎";
        public const string ThinkingFace = "🤔";
        public const string FaceWithRollingEyes = "🙄";
        public const string GrinningFace = "😀";
        public const string WinkingFace = "😉";
        public const string CryingFace = "😭";
        public const string LoudlyCryingFace = "😭";
        public const string FaceWithMedicalMask = "😷";
        public const string FaceWithMonocle = "🧐";
        public const string ZanyFace = "🤪";
        public const string StarStruck = "🤩";
        public const string FaceWithHandOverMouth = "🤭";
        public const string ShushingFace = "🤫";
        public const string FaceWithSymbolsOnMouth = "🤬";
        public const string ExplodingHead = "🤯";
        public const string FaceWithThermometer = "🤒";
        public const string FaceWithHeadBandage = "🤕";
        public const string MoneyMouthFace = "🤑";
        public const string HuggingFace = "🤗";
        public const string FaceWithPartyHornAndPartyHat = "🥳";
        public const string SmilingFaceWithHalo = "😇";
        public const string Cowbell = "🔔";
        public const string ClappingHands = "👏";
        public const string ThumbsUp = "👍";
        public const string ThumbsDown = "👎";
        public const string RaisedHands = "🙌";
        public const string FoldedHands = "🙏";
        public const string VictoryHand = "✌️";
        public const string OKHand = "👌";
        public const string FlexedBiceps = "💪";
        public const string Fire = "🔥";
        public const string HundredPoints = "💯";
        public const string Sparkles = "✨";
        public const string Rainbow = "🌈";
        public const string Sun = "☀️";
        public const string Moon = "🌙";
        public const string Star = "⭐";
        public const string Heart = "❤️";
        public const string BrokenHeart = "💔";
        public const string GrinningFaceWithSmilingEyes = "😁";
        public const string FaceWithTearsOfJoy2 = "😂";
        public const string SmilingFaceWithOpenMouth = "😃";
        public const string SmilingFaceWithOpenMouthAndSmilingEyes = "😄";
        public const string SmilingFaceWithOpenMouthAndColdSweat = "😅";
        public const string SmilingFaceWithOpenMouthAndTightlyClosedEyes = "😆";
        public const string WinkingFaceWithTongue = "😜";
        public const string ZanyFace2 = "🤪";
        public const string SmilingFaceWithSunglasses2 = "😎";
        public const string NerdFace = "🤓";
        public const string FaceWithMonocle2 = "🧐";
        public const string ThinkingFace2 = "🤔";
        public const string FaceWithRaisedEyebrow = "🤨";
        public const string FaceWithRollingEyes2 = "🙄";
        public const string SmirkingFace = "😏";
        public const string UnamusedFace = "😒";
        public const string DowncastFaceWithSweat = "😓";
        public const string PensiveFace = "😔";
        public const string ConfusedFace = "😕";
        public const string WorriedFace = "😟";
        public const string SlightlyFrowningFace = "🙁";
        public const string FrowningFace = "☹️";
        public const string OpenMouth = "😮";
        public const string HushedFace = "😯";
        public const string AstonishedFace = "😲";
        public const string FlushedFace = "😳";
        public const string PleadingFace = "🥺";
        public const string CryingFace2 = "😢";
        public const string LoudlyCryingFace2 = "😭";
        public const string FaceScreamingInFear = "😱";
        public const string FearfulFace = "😨";
        public const string AnxiousFaceWithSweat = "😰";
        public const string SadButRelievedFace = "😥";
        public const string PerseveringFace = "😣";
        public const string DisappointedButRelievedFace = "😓";
        public const string DowncastFaceWithTear = "😢";
        public const string CryingFace3 = "😭";
        public const string FaceWithSteamFromNose = "😤";
        public const string AngryFace = "😠";
        public const string PoutingFace = "😡";
        public const string FaceWithSymbolsOnMouth2 = "🤬";
        public const string ExplodingHead2 = "🤯";
        public const string SmilingFaceWithHorns = "😈";
        public const string Imp = "👿";
        public const string KissingFaceWithSmilingEyes = "😚";
        public const string HotFace = "\U0001f975";
        public const string ColdFace = "\U0001f976";
        public const string WoozyFace = "\U0001f974";
        public const string DizzyFace = "&#x1f635;";
        public const string ExplodingHead3 = "&#x1f92f;";
        public const string FaceWithMedicalMask2 = "😷";
        public const string FaceWithThermometer2 = "&#x1f912;";
        public const string FaceWithHeadBandage2 = "&#x1f915;";
        public const string NauseatedFace = "&#x1f922;";
        public const string FaceVomiting = "\U0001f92e";
        public const string SneezingFace = "&#x1f927;";
        public const string HotBeverage = "☕";
        public const string TeacupWithoutHandle = "🍵";
        public const string BeerMug = "🍺";
        public const string ClinkingBeerMugs = "🍻";
        public const string WineGlass = "🍷";
        public const string CocktailGlass = "🍸";
        public const string TropicalDrink = "🍹";
        public const string TumblerGlass = "🥃";
        public const string ForkAndKnife = "🍴";
        public const string Pizza = "🍕";
        public const string Hamburger = "🍔";
        public const string FrenchFries = "🍟";
        public const string Taco = "🌮";
        public const string Burrito = "🌯";
        public const string Salad = "🥗";
        public const string Poo = "💩";
        public const string Robot = "🤖";
        public const string Ghost = "👻";
        public const string Alien = "👽";
        public const string Skull = "💀";
        public const string PartyPopper = "🎉";
        public const string Balloon = "🎈";
        public const string ConfettiBall = "🎊";
        public const string Gift = "🎁";
        public const string BirthdayCake = "🎂";
        public const string JackOLantern = "🎃";
        public const string ChristmasTree = "🎄";
        public const string SantaClaus = "🎅";
        public const string Fireworks = "🎆";
        public const string Sparkler = "🎇";
        public const string Ribbon = "🎀";
        public const string Medal = "🏅";
        public const string Trophy = "🏆";
        public const string SportsMedal = "🥇";
        public const string FirstPlaceMedal = "🥇";
        public const string KissMark = "💋";
        public const string Bomb = "💣";
        public const string CrossedFingers = "🤞";
        public const string Zzz = "💤";
        public const string Wave = "👋";
        public const string CallMeHand = "🤙";
        public const string WritingHand = "✍️";
        public const string NailPolish = "💅";
        public const string Selfie = "🤳";
        public const string WavingHand = "👋";
        public const string Handshake = "🤝";
        public const string RaisedFist = "✊";
        public const string VictoryHand2 = "✌️";
        public const string LoveYouGesture = "🤟";
        public const string BackhandIndexPointingLeft = "👈";
        public const string BackhandIndexPointingRight = "👉";
        public const string BackhandIndexPointingUp = "👆";
        public const string BackhandIndexPointingDown = "👇";
        public const string MiddleFinger = "🖕";
        public const string OncomingFist = "👊";
        public const string RaisedBackOfHand = "🤚";
        public const string VulcanSalute = "🖖";
        public const string SignOfTheHorns = "🤘";
        public const string WritingHand2 = "✍️";
        public const string IndexPointingUp = "☝️";
        public const string IndexPointingDown = "👇";
        public const string IndexPointingLeft = "👈";
        public const string IndexPointingRight = "👉";
        public const string ThumbsUp2 = "👍";
        public const string ThumbsDown2 = "👎";
        public const string ClappingHands2 = "👏";
        public const string OpenHands = "👐";
        public const string PalmsUpTogether = "🤲";
        public const string FoldedHands2 = "🙏";
        public const string FlexedBiceps2 = "💪";
        public const string Girl = "👧";
        public const string Boy = "👦";
        public const string Person = "🧑";
        public const string Man = "👨";
        public const string Woman = "👩";
        public const string OlderPerson = "🧓";
        public const string OldMan = "👴";
        public const string OldWoman = "👵";
        public const string Baby = "👶";
        public const string PersonWithCrown = "👸";
        public const string Prince = "🤴";
        public const string PersonWithVeil = "👰";
        public const string ManInTuxedo = "🤵";
        public const string PoliceOfficer = "👮";
        public const string Detective = "🕵️";
        public const string FireFighter = "👩‍🚒";
        public const string PersonFrowning = "🙍";
        public const string PersonPouting = "🙎";
        public const string PersonGesturingNo = "🙅";
        public const string PersonGesturingOk = "🙆";
        public const string PersonTippingHand = "💁";
        public const string PersonRaisingHand = "🙋";
        public const string ManStudent = "👨‍🎓";
        public const string WomanStudent = "👩‍🎓";
        public const string ManTeacher = "👨‍🏫";
        public const string WomanTeacher = "👩‍🏫";
        public const string ManOfficeWorker = "👨‍💼";
        public const string WomanOfficeWorker = "👩‍💼";
        public const string ManMechanic = "👨‍🔧";
        public const string WomanMechanic = "👩‍🔧";
        public const string ManFactoryWorker = "👨‍🏭";
        public const string WomanFactoryWorker = "👩‍🏭";
        public const string ManCook = "👨‍🍳";
        public const string WomanCook = "👩‍🍳";
        public const string ManTechnologist = "👨‍💻";
        public const string WomanTechnologist = "👩‍💻";
        public const string ManArtist = "👨‍🎨";
        public const string WomanArtist = "👩‍🎨";
        public const string ManPilot = "👨‍✈️";
        public const string WomanPilot = "👩‍✈️";
        public const string ManAstronaut = "👨‍🚀";
        public const string WomanAstronaut = "👩‍🚀";
        public const string ManFirefighter = "👨‍🚒";
        public const string WomanFirefighter = "👩‍🚒";
        public const string HealthWorker = "🧑‍⚕️";
        public const string ManHealthWorker = "👨‍⚕️";
        public const string WomanHealthWorker = "👩‍⚕️";
        public const string PoliceOfficer2 = "👮";
        public const string ManPoliceOfficer = "👮‍♂️";
        public const string WomanPoliceOfficer = "👮‍♀️";
        public const string Detective2 = "🕵️";
        public const string ManDetective = "🕵️‍♂️";
        public const string WomanDetective = "🕵️‍♀️";
        public const string Guard = "💂";
        public const string ManGuard = "💂‍♂️";
        public const string WomanGuard = "💂‍♀️";
        public const string ConstructionWorker = "👷";
        public const string ManConstructionWorker = "👷‍♂️";
        public const string WomanConstructionWorker = "👷‍♀️";
        public const string PregnantWoman = "🤰";
        public const string BreastFeeding = "🤱";
        public const string BabyAngel = "👼";
        public const string SantaClaus2 = "🎅";
        public const string MrsClaus = "🤶";
        public const string Superhero = "🦸";
        public const string ManSuperhero = "🦸‍♂️";
        public const string WomanSuperhero = "🦸‍♀️";
        public const string Supervillain = "🦹";
        public const string ManSupervillain = "🦹‍♂️";
        public const string WomanSupervillain = "🦹‍♀️";
        public const string Zombie = "🧟";
        public const string ManZombie = "🧟‍♂️";
        public const string WomanZombie = "🧟‍♀️";
        public const string PersonGettingHaircut = "💇";
        public const string ManGettingHaircut = "💇‍♂️";
        public const string WomanGettingHaircut = "💇‍♀️";
        public const string PersonGettingMassage = "💆";
        public const string ManGettingMassage = "💆‍♂️";
        public const string WomanGettingMassage = "💆‍♀️";
        public const string PersonInSteamyRoom = "🧖";
        public const string ManInSteamyRoom = "🧖‍♂️";
        public const string WomanInSteamyRoom = "🧖‍♀️";
        public const string PersonClimbing = "🧗";
        public const string ManClimbing = "🧗‍♂️";
        public const string WomanClimbing = "🧗‍♀️";
        public const string PersonFencing = "🤺";
        public const string HorseRacing = "🏇";
        public const string Skier = "⛷️";
        public const string Snowboarder = "🏂";
        public const string PersonWalking = "🚶";
        public const string ManWalking = "🚶‍♂️";
        public const string WomanWalking = "🚶‍♀️";
        public const string PersonRunning = "🏃";
        public const string ManRunning = "🏃‍♂️";
        public const string WomanRunning = "🏃‍♀️";
        public const string PersonDancing = "💃";
        public const string ManDancing = "🕺";
        public const string WomanDancing = "💃";
        public const string PersonInSuitLevitating = "🕴️";
        public const string PeopleHugging = "🫂";
        public const string PersonGolfing = "🧍";
        public const string ManGolfing = "🧍‍♂️";
        public const string WomanGolfing = "🧍‍♀️";
        public const string PersonSurfing = "🏄";
        public const string ManSurfing = "🏄‍♂️";
        public const string WomanSurfing = "🏄‍♀️";
        public const string PersonRowingBoat = "🚣";
        public const string ManRowingBoat = "🚣‍♂️";
        public const string WomanRowingBoat = "🚣‍♀️";
        public const string PersonSwimming = "🏊";
        public const string ManSwimming = "🏊‍♂️";
        public const string WomanSwimming = "🏊‍♀️";
        public const string PersonBiking = "🚴";
        public const string ManBiking = "🚴‍♂️";
        public const string WomanBiking = "🚴‍♀️";
        public const string PersonMountainBiking = "🚵";
        public const string PersonLiftingWeights = "🏋️";
        public const string ManLiftingWeights = "🏋️‍♂️";
        public const string WomanLiftingWeights = "🏋️‍♀️";
        public const string PersonPlayingHandball = "🤾";
        public const string ManPlayingHandball = "🤾‍♂️";
        public const string WomanPlayingHandball = "🤾‍♀️";
        public const string PersonJuggling = "🤹";
        public const string ManJuggling = "🤹‍♂️";
        public const string WomanJuggling = "🤹‍♀️";
        public const string PersonInLotusPosition = "🧘";
        public const string ManInLotusPosition = "🧘‍♂️";
        public const string WomanInLotusPosition = "🧘‍♀️";
        public const string PersonTakingBath = "🛀";
        public const string PersonInBed = "🛌";
        public const string PeopleWithBunnyEars = "👯";
        public const string MenWithBunnyEars = "👯‍♂️";
        public const string WomenWithBunnyEars = "👯‍♀️";
        public const string WomanAndManHoldingHands = "👫";
        public const string TwoWomenHoldingHands = "👭";
        public const string TwoMenHoldingHands = "👬";
        public const string Family = "👪";
        public const string ManAndWomanHoldingHands = "👫";
        public const string WomanAndWomanHoldingHands = "👭";
        public const string ManAndManHoldingHands = "👬";
        public const string CoupleWithHeart = "💑";
        public const string CoupleWithHeartWomanMan = "💑‍👩‍❤️‍👨";
        public const string CoupleWithHeartWomanWoman = "💑‍👩‍❤️‍";
        public const string PersonTalking = "🗣️";
        public const string BustInSilhouette = "👤";
        public const string BustsInSilhouette = "👥";
        public const string Footprints = "👣";
        public const string Eye = "👁️";
        public const string Ear = "👂";
        public const string Nose = "👃";
        public const string Mouth = "👄";
        public const string Tongue = "👅";
        public const string Brain = "🧠";
        public const string PersonInBed2 = "🛌";
        public const string WomanHoldingHands = "👭";
        public const string ManHoldingHands = "👬";
        public const string Kiss = "💏";
        public const string KissWomanMan = "&#x1f468;";
        public const string SpeakingHead = "🗣️";
        public const string FootPrints = "👣";
        public const string MoneyBag = "💰";
        public const string CreditCard = "💳";
        public const string ShoppingCart = "🛒";
        public const string ShoppingBags = "🛍️";
        public const string Package = "📦";
        public const string Receipt = "🧾";
        public const string Ticket = "🎟️";
        public const string ShoppingTrolley = "🛒";
        public const string MonkeyFace = "🐵";
        public const string DogFace = "🐶";
        public const string CatFace = "🐱";
        public const string MouseFace = "🐭";
        public const string HamsterFace = "🐹";
        public const string RabbitFace = "🐰";
        public const string FoxFace = "🦊";
        public const string BearFace = "🐻";
        public const string PandaFace = "🐼";
        public const string KoalaFace = "🐨";
        public const string TigerFace = "🐯";
        public const string LionFace = "🦁";
        public const string CowFace = "🐮";
        public const string PigFace = "🐷";
        public const string FrogFace = "🐸";
        public const string Octopus = "🐙";
        public const string Fish = "🐟";
        public const string Whale = "🐳";
        public const string Dolphin = "🐬";
        public const string HorseFace = "🐴";
        public const string WolfFace = "&#x1f43a;";
        public const string Deer = "&#x1f98c;";
        public const string UnicornFace = "&#x1f984;";
        public const string Bee = "&#x1f41d;";
        public const string LadyBeetle = "&#x1f41e;";
        public const string Butterfly = "&#x1f98b;";
        public const string Snail = "&#x1f40c;";
        public const string Ant = "&#x1f41c;";
        public const string Spider = "&#x1f577;";
        public const string Scorpion = "&#x1f982;";
        public const string Crab = "&#x1f980;";
        public const string Snake = "&#x1f40d;";
        public const string Turtle = "&#x1f422;";
        public const string Lizard = "&#x1f98e;";
        public const string Tortoise = "&#x1f422;";
        public const string Bat = "&#x1f987;";
        public const string PawPrint= "&#x1f43e;";
        public const string Chipmunk = "&#x1f43f;";
        public const string Badger = "&#x1f9a1;";
        public const string Otter = "&#x1f9a6;";
        public const string Beaver = "&#x1f9ab;";
        public const string Hedgehog = "&#x1f994;";
        public const string Kangaroo = "&#x1f998;";
        public const string Llama = "&#x1f999;"; 
        public const string Peacock = "&#x1f99a;";
        public const string Parrot = "&#x1f99c;";
        public const string Raccoon = "&#x1f99d;";
        public const string Sloth = "&#x1f9a5;";
        public const string Otter2 = "&#x1f9a6;";
        public const string Skunk = "&#x1f9a8;";
        public const string Flamingo = "&#x1f9a9;";
        public const string Orangutan = "&#x1f9a7;";
        public const string Slug = "&#x1f40c;";
        public const string Mosquito = "&#x1f99f;";
        public const string Microbe = "&#x1f9a0;";
        public const string Engle = "&#x1f985;";
        public const string Duck = "&#x1f986;";
        public const string Swan = "&#x1f9a2;";
        public const string Owl = "&#x1f989;";
        public const string Dodo = "&#x1f9a4;";
        public const string Feather = "&#x1fab6;";
        public const string Cooking = "🍳";
        public const string OKButton = "&#x1f197;";
        public const string UpButton = "&#x1f199;";
        public const string DownButton = "&#x1f199;";
        public const string CoolButton = "&#x1f192;";
        public const string NewButton = "&#x1f195;";
        public const string FreeButton = "&#x1f193;";
        public const string Information = "&#x2139;";
        public const string IdButton = "&#x1f194;";
        public const string EndButton = "&#x1f51a;";
        public const string BackButton = "&#x1f519;";
        public const string OnButton = "&#x1f51b;";
        public const string TopArrow = "&#x1f53c;";
        public const string DownArrow = "&#x1f53d;";
        public const string DoubleUpArrow = "&#x23eb;";
        public const string DoubleDownArrow = "&#x23ec;";
        public const string ArrowPointingRightwardsThenCurvingUpwards = "&#x2934;";
        public const string ArrowPointingRightwardsThenCurvingDownwards = "&#x2935;";
        public const string ArrowPointingRightwardsThenCurvingUpwards2 = "&#x2934;";
        public const string ArrowPointingRightwardsThenCurvingDownwards2 = "&#x2935;";
        public const string LeftArrow = "&#x2b05;";
        public const string RightArrow = "&#x27a1;";
        public const string UpArrow = "&#x2b06;";
        public const string UpRightArrow = "&#x2197;";
        public const string DownRightArrow = "&#x2198;";
        public const string DownLeftArrow = "&#x2199;";
        public const string UpLeftArrow = "&#x2196;";
        public const string RedCircle = "&#x1f534;";
        public const string BlueCircle = "&#x1f535;";
        public const string GreenCircle = "&#x1f7e2;";
        public const string YellowCircle = "&#x1f7e1;";
        public const string PurpleCircle = "&#x1f7e3;";
        public const string OrangeCircle = "&#x1f7e0;";
        public const string BlackCircle = "&#x26ab;";
        public const string WhiteCircle = "&#x26aa;";
        public const string BrownCircle = "&#x1f7e4;";
        public const string RedSquare = "&#x1f7e5;";
        public const string BlueSquare = "&#x1f7e6;";
        public const string GreenSquare = "&#x1f7e9;";
        public const string YellowSquare = "&#x1f7e8;";
        public const string PurpleSquare = "&#x1f7ea;";
        public const string OrangeSquare = "&#x1f7e7;";
        public const string BlackSquare = "&#x2b1b;";
        public const string WhiteSquare = "&#x2b1c;";
        public const string BrownSquare = "&#x1f7eb;";
        public const string RedTrianglePointedUp = "&#x1f53a;";
        public const string RedTrianglePointedDown = "&#x1f53b;";
        public const string Warning = "&#x26a0;";
        public const string ChildrenCrossing = "&#x1f6b8;";
        public const string NoEntry = "&#x26d4;";
        public const string Prohibited = "&#x1f6ab;";
        public const string NoBicycles = "&#x1f6b3;";
        public const string NoSmoking = "&#x1f6ad;";
        public const string NoLittering = "&#x1f6af;";
        public const string NonPotableWater = "&#x1f6b1;";
        public const string NoPedestrians = "&#x1f6b7;";
        public const string NoMobilePhones = "&#x1f4f5;";
        public const string NoOneUnderEighteen = "&#x1f51e;";
        public const string CheckMark = "&#x2705;";
        public const string CrossMark = "&#x274c;";
        public const string HeavyCheckMark = "&#x2714;";
        public const string HeavyMultiplicationX = "&#x2716;";
        public const string Plus = "➕";
        public const string Minus = "&#x2796;";
        public const string Division = "&#x2797;";
        public const string MoblePhone = "&#x1f4f1;";
        public const string MobilePhoneWithArrow = "&#x1f4f2;";
        public const string VibrationMode = "&#x1f4f3;";
        public const string MobilePhoneOff = "&#x1f4f4;";
        public const string AntennaWithBars = "&#x1f4f6;";
        public const string Camera = "&#x1f4f7;";
        public const string CameraWithFlash = "&#x1f4f8;";
        public const string VideoCamera = "&#x1f4f9;";
        public const string MovieCamera = "&#x1f3a5;";
        public const string Television = "&#x1f4fa;";
        public const string Radio = "&#x1f4fb;";
        public const string Videocassette = "&#x1f4fc;";
        public const string MagnifyingGlassTiltedLeft = "&#x1f50d;";
        public const string MagnifyingGlassTiltedRight = "&#x1f50e;";
        public const string LightBulb = "&#x1f4a1";
        public const string Flashlight = "&#x1f526";
        public const string Candle = "&#x1f56f";
        public const string Wastebasket = "&#x1f5d1";
        public const string MicroPhone = "&#x1f3a4";
        public const string HeadPhone = "&#x1f3a7";
        public const string MusicalNote = "&#x1f3b5";
        public const string MusicalNotes = "&#x1f3b6";
        public const string SpeakerLowVolume = "&#x1f508";
        public const string SpeakerMediumVolume = "&#x1f509";
        public const string SpeakerHighVolume = "&#x1f50a";
        public const string SpeakerMuted = "&#x1f507";
        public const string Battery = "&#x1f50b";
        public const string ElectricPlug = "&#x1f50c";
        public const string Laptop = "&#x1f4bb";
        public const string DesktopComputer = "&#x1f5a5";
        public const string Printer = "&#x1f5a8";
        public const string Keyboard = "&#x2328";
        public const string ComputerMouse = "&#x1f5b1";
        public const string Trackball = "&#x1f5b2";
        public const string Minidisc = "&#x1f4bd";
        public const string FloppyDisk = "&#x1f4be";
        public const string OpticalDisk = "&#x1f4bf";
        public const string Dvd = "&#x1f4c0";
        public const string FileFolder = "&#x1f4c1";
        public const string OpenFileFolder = "&#x1f4c2";
        public const string PageWithCurl = "&#x1f4c3";
        public const string PageFacingUp = "&#x1f4c4";
        public const string Calendar = "&#x1f4c5";
        public const string TearOffCalendar = "&#x1f4c6";
        public const string CardIndex = "&#x1f4c7";
        public const string ChartIncreasing = "&#x1f4c8";
        public const string ChartDecreasing = "&#x1f4c9";
        public const string BarChart = "&#x1f4ca";
        public const string Clipboard = "&#x1f4cb";
        public const string Pushpin = "&#x1f4cc;";
        public const string RoundPushpin = "&#x1f4cd";
        public const string Paperclip = "&#x1f4ce";
        public const string LinkedPaperclips = "&#x1f587";
        public const string StraightRuler = "&#x1f4cf";
        public const string TriangularRuler = "&#x1f4d0";   
        public const string BookmarkTabs = "&#x1f4d1";
        public const string Ledger = "&#x1f4d2";
        public const string Notebook = "&#x1f4d3";
        public const string NotebookWithDecorativeCover = "&#x1f4d4";
        public const string ClosedBook = "&#x1f4d5";
        public const string OpenBook = "&#x1f4d6";
        public const string GreenBook = "&#x1f4d7";
        public const string BlueBook = "&#x1f4d8";
        public const string OrangeBook = "&#x1f4d9";
        public const string Books = "&#x1f4da";
        public const string NameBadge = "&#x1f4db";
        public const string Scroll = "&#x1f4dc";
        public const string USSDollarBanknote = "&#x1f4b5";
        public const string MoneyWithWings = "&#x1f4b8";
        public const string USDEuroBanknote = "&#x1f4b6";
        public const string USDPoundBanknote = "&#x1f4b7";
        public const string MoneyBag2 = "&#x1f4b0";
        public const string CreditCard2 = "&#x1f4b3";
        public const string Receipt2 = "&#x1f9fe";
        public const string ChartIncreasing2 = "&#x1f4c8";
        public const string ChartDecreasing2 = "&#x1f4c9";
        public const string BarChart2 = "&#x1f4ca";
        public const string CurrencyExchange = "&#x1f4b1";
        public const string HeavyDollarSign = "&#x1f4b2";
        public const string EuroSign = "&#x20ac";
        public const string PoundSign = "&#xa3";
        public const string YenSign = "&#xa5";
        public const string IndianRupeeSign = "&#x20b9";
        public const string KoreanWonSign = "&#x20a9";
        public const string BitcoinSign = "&#x20bf";
        public const string Ambulance = "&#x1f691";
        public const string FireEngine = "&#x1f692";
        public const string PoliceCar = "&#x1f693";
        public const string Taxi = "&#x1f695";
        public const string Automobile = "&#x1f697";
        public const string RecreationalVehicle = "&#x1f3cd";
        public const string DeliveryTruck = "&#x1f69a";
        public const string ArticulatedLorry = "&#x1f69b";
        public const string Tractor = "&#x1f69c";
        public const string Bicycle = "&#x1f6b2";
        public const string MotorScooter = "&#x1f6f5";
        public const string Motorcycle = "&#x1f3cd";
        public const string AutoRickshaw = "&#x1f6fa";
        public const string Bus = "&#x1f68c";
        public const string Trolleybus = "&#x1f68e";
        public const string Minibus = "&#x1f690";
        public const string Tram = "&#x1f68a";
        public const string Monorail = "&#x1f69d";
        public const string MountainRailway = "&#x1f69e;";
        public const string Train = "&#x1f686;";
        public const string HighSpeedTrain = "&#x1f684;";
        public const string BulletTrain = "&#x1f685;";
        public const string LightRail = "&#x1f688;";
        public const string Station = "&#x1f689;";
        public const string Metro = "&#x1f687;";
        public const string RailwayCar = "&#x1f683;";
        public const string Ship = "&#x1f6a2;";
        public const string Speedboat = "&#x1f6a4;";
        public const string Ferry = "&#x26f4;";
        public const string MotorBoat = "&#x1f6e5;";
        public const string Sailboat = "&#x26f5;";
        public const string Canoe = "&#x1f6f6;";
        public const string Kayak = "&#x1f6f6;";
        public const string Rowboat = "&#x1f6a3;";
        public  const string Anchor = "&#x2693;";
        public const string Rocket = "&#x1f680;";
        public const string FlyingSaucer = "&#x1f6f8;";
        public const string Airplane = "&#x2708;";
        public const string SmallAirplane = "&#x1f6e9;";
        public const string AirplaneDeparture = "&#x1f6eb;";
        public const string AirplaneArrival = "&#x1f6ec;";
        public const string Parachute = "&#x1fa82;";
        public const string Seat = "&#x1f4ba;";
        public const string Helicopter = "&#x1f681;";
        public const string SuspensionRailway = "&#x1f69f;";
        public const string MountainCableway = "&#x1f6a0;";
        public const string AerialTramway = "&#x1f6a1;";
        public const string Satellite = "&#x1f6f0;";
        public const string PassengerShip = "&#x1f6f3;";
        public const string Motorway = "&#x1f6e3;";
        public const string RailwayTrack = "&#x1f6e4;";
        public const string OilDrum = "&#x1f6e2;";
        public const string Tool = "🔨";
        public const string Science = "⚗";
        public const string Medical = "💊";
        public const string Reflective = "🧠";
        public const string JoyFul = "😄";
        public const string FaceSmiling ="😀";
        public const string PlayButton = "▶";
        public const string FaceAaffection = "😍";
        public const string FaceTongue = "😋";
        public const string EmotionsTagHappy = "Happy";
        public const string EmotionsTagHappyColor = "#FFE066"; 
        public const string EmotionsTagSad = "Sad";
        public const string EmotionsTagSadColor = "#2196F3";
        public const string EmotionsTagAngry = "Angry";
        public const string EmotionsTagAngryColor = "#FF3F00";
        public const string EmotionsTagCalm = "Calm";
        public const string EmotionsTagCalmColor = "#7BC2BC";
        public const string EmotionsTagConfused = "Confused";
        public const string EmotionsTagConfusedColor = "#94B3C4";
        public const string EmotionsTagNeutral = "Neutral";
        public const string EmotionsTagNeutralColor = "#EAE7DC";
        public const string EmotionsTagEnergized = "Energized";
        public const string EmotionsTagEnergizedColor = "#FFFF00";
        public const string EmotionsTagReflective = "Reflective";
        public const string EmotionsTagReflectiveColor = "#C7A0CB";
        public const string EmotionsTagAnxious = "Anxious";
        public const string EmotionsTagAnxiousColor = "#8C92AC";
        public const string EmotionsTagHopeful = "Hopeful";
        public const string EmotionsTagHopefulColor = "#9500FF";
        public const string EmotionsTagJoyful = "Joyful";
        public const string EmotionsTagJoyfulColor = "#FF007F";

        public const string EmotionsTagLonely = "Lonely";
        public const string EmotionsTagLonelyfulColor = "#4B0082";
        public const string EmotionsTagGrateful = "Grateful";
        public const string EmotionsTagGratefulColor = "#FFE5B4";
        public const string EmotionsTagPeaceful = "Peaceful";
        public const string EmotionsTagPeacefulColor = "#00FF7F";
        public const string EmotionsTagLoved = "Loved";
        public const string EmotionsTagLovedColor = "#FFDEE9";

        public static string HtmlEntityToUnicodeEscape(string htmlEntity)
        {
            if (htmlEntity.StartsWith("&#x"))// && htmlEntity.EndsWith(";"))
                return string.Empty;
                // Extract the hex value from the HTML entity
                //if (htmlEntity.StartsWith("&#x") && htmlEntity.EndsWith(";"))
            //{
              //  string hex = htmlEntity.Substring(3, htmlEntity.Length - 4);
               // int codePoint = int.Parse(hex, NumberStyles.HexNumber);
                //return $"\\U{codePoint:X8}";
           // }
            return htmlEntity ;

            //throw new ArgumentException("Invalid HTML entity format.");
        }

        public static async Task<Color> GetMoodBackGroundColor(string mood)
        {
            var backGroundColor = mood switch
            {
                "Happy" => Color.FromArgb("#FFE066"),
                "Sad" => Color.FromArgb("#2196F3"),
                "Angry" => Color.FromArgb("#FF3F00"),
                "Calm" => Color.FromArgb("#7BC2BC"),
                "Confused" => Color.FromArgb("#94B3C4"),
                "Neutral" => Color.FromArgb("#D3D3D3"),
                "Energized" => Color.FromArgb("#FFFF00"),
                "Reflective" => Color.FromArgb("#C7A0CB"),
                "Anxious" => Color.FromArgb("#8C92AC"),
                "Hopeful" => Color.FromArgb("#9500FF"),
                "Joyful" => Color.FromArgb("#FF007F"),
                "Lonely" => Color.FromArgb("#4B0082"),
                "Grateful" => Color.FromArgb("#FFE5B4"),
                "Peaceful" => Color.FromArgb("#00FF7F"),
                "Loved" => Color.FromArgb("#FFDEE9"),


                _ => Colors.Gray
            };
            return backGroundColor;
        }
        public static async Task<string> GetMoodLabel(string mood)
        {
            var label = mood switch
            {
                "Happy" => $"Journal or talk about why your emontions are Happy {Utilites.EmojiTags.Happy} today..",
                "Sad" => $"Journal or talk about why your emontions are Sad {Utilites.EmojiTags.Sad} today..",
                "Angry" => $"Journal or talk about why your emontions are Angry {Utilites.EmojiTags.AngryFace} today.",
                "Calm" => $"Journal or talk about why your emontions are Calm {Utilites.EmojiTags.Calm} today..",
                "Confused" => $"Journal or talk about why your emontions are Confused {Utilites.EmojiTags.Confused} today..",
                "Neutral" => $"Journal or talk about why your emontions are Neutral {Utilites.EmojiTags.Neutral} today..",
                "Energized" => $"Journal or talk about why your emontions are Energized {Utilites.EmojiTags.Energetic} today..",
                "Reflective" => $"Journal or talk about why your emontions are Reflective {Utilites.EmojiTags.Reflective} today..",
                "Anxious" => $"Journal or talk about why your emontions are Anxious {Utilites.EmojiTags.AnxiousFaceWithSweat} today..",
                "Hopeful" => $"Journal or talk about why your emontions are HopeFul {Utilites.EmojiTags.Hopeful} today..",
                "Joyful" => $"Journal or talk about why your emontions are JoyFul {Utilites.EmojiTags.FaceWithTearsOfJoy} today..",
                "Lonely" => $"Journal or talk about why your emontions are Lonely {Utilites.EmojiTags.Lonely} today..",
                "Grateful" => $"Journal or talk about why your emontions are Grateful {Utilites.EmojiTags.Grateful} today..",
                "Peaceful" => $"Journal or talk about why your emontions are Peaceful {Utilites.EmojiTags.Peaceful} today..",
                "Loved" => $"Journal or talk about why your emontions are Loved {Utilites.EmojiTags.Loved} today..",

                _ => $"Journal or talk about why your emontions are Uncertain {Utilites.EmojiTags.LightBulb} today.."
            };
            return label;
        }
        public static async Task<string> GetMoodTag(string mood)
        {
            var moodTag = mood switch
            {
                "Happy" => Utilites.EmojiTags.Happy,
                "Sad" => Utilites.EmojiTags.Sad,
                "Angry" => Utilites.EmojiTags.AngryFace,
                "Calm" => Utilites.EmojiTags.Calm,
                "Confused" => Utilites.EmojiTags.Confused,
                "Neutral" => Utilites.EmojiTags.Neutral,
                "Energized" => Utilites.EmojiTags.Energetic,
                "Reflective" => Utilites.EmojiTags.Reflective,
                "Anxious" => Utilites.EmojiTags.AnxiousFaceWithSweat,
                "Hopeful" => Utilites.EmojiTags.Hopeful,
                "Joyful" => Utilites.EmojiTags.FaceWithTearsOfJoy,
                "Lonely" => Utilites.EmojiTags.Lonely,
                "Grateful" => Utilites.EmojiTags.Grateful,
                "Peaceful" => Utilites.EmojiTags.Peaceful,
                "Loved" => Utilites.EmojiTags.Loved,
                _ => Utilites.EmojiTags.LightBulb
            };
            return moodTag;
        }
        public static async Task<Tuple<Color,string,string>> GetMoodTagColorLabel(string mood)

        {
           var backGroundColor = await GetMoodBackGroundColor(mood);
            var label = await GetMoodLabel(mood);
            var moodTag = await GetMoodTag(mood);



            return Tuple.Create(backGroundColor, label, moodTag);
        }


    }
}
