//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManualIndexingTemp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CS")]
        public string DefaultScanStationID {
            get {
                return ((string)(this["DefaultScanStationID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55555")]
        public string DefaultIndexNumber {
            get {
                return ((string)(this["DefaultIndexNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^.{14}$|^.{18}$")]
        public string OldIndexNumberRegex {
            get {
                return ((string)(this["OldIndexNumberRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"You have entered in an accession number using the old format.\nRecords starting 9/19/2010 should be entered as follows:\n{9 digit financial number}\n{6 digit client code}{9 digit patient id}\n{6 digit client code}{9 digit requisition number}\nTo continue using the old format, click Ok\nTo enter a different accession number, click Cancel")]
        public string OldIndexNumberMessage {
            get {
                return ((string)(this["OldIndexNumberMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^[a-z A-Z \\d \\- _]{9}$|^[a-z A-Z \\d \\- _]{15}$|^[a-z A-Z \\d \\- _]{18}$|^[a-z A-Z " +
            "\\d \\- _]{16}$")]
        public string ValidIndexNumberRegex {
            get {
                return ((string)(this["ValidIndexNumberRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^(\\d{9})\\1+$")]
        public string ExtraPromptRegex {
            get {
                return ((string)(this["ExtraPromptRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("You have entered an index number that requires an additional check.")]
        public string ExtraPromptMessage {
            get {
                return ((string)(this["ExtraPromptMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\Archives\\NYP\\LabReqs\\")]
        public string ArchiveRoot {
            get {
                return ((string)(this["ArchiveRoot"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UploadToSP {
            get {
                return ((bool)(this["UploadToSP"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^[34]\\d{9}$|^[4]\\d{7}$|^[5]\\d{7}$|^[6]\\d{6}$|^[6]\\d{7}$|^[W][C]\\d{4}$|^[3]\\d{7}$|" +
            "^[1]\\d{9}$|^WC\\d{5}$|^7\\d{6}$|5\\d{8}$|^20\\d{8}$|^63\\d{6}$|^20\\d{8}$|\\d{9}$")]
        public string ValidRequisitionNumberRegx {
            get {
                return ((string)(this["ValidRequisitionNumberRegx"]));
            }
            set {
                this["ValidRequisitionNumberRegx"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{ApplicationDir}\\Local\\EdocsManualIndexing\\")]
        public string LogFolder {
            get {
                return ((string)(this["LogFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int DaysToKeepLogFiles {
            get {
                return ((int)(this["DaysToKeepLogFiles"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp.gmail.com")]
        public string EmailServer {
            get {
                return ((string)(this["EmailServer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AlertSender@edocsusa.com")]
        public string EmailFrom {
            get {
                return ((string)(this["EmailFrom"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6746edocs")]
        public string EmailPassword {
            get {
                return ((string)(this["EmailPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("587")]
        public int EmailPort {
            get {
                return ((int)(this["EmailPort"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dan.Roper@edocsusa.com")]
        public string EmailTo {
            get {
                return ((string)(this["EmailTo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EmailCC {
            get {
                return ((string)(this["EmailCC"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{ErrorSuccess} Running ManualIndexing runtime {runDate}")]
        public string EmailSubject {
            get {
                return ((string)(this["EmailSubject"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Call e-Docs USA support @(406)-565-3465 and tell them upload process did not star" +
            "t.")]
        public string EdocsSupport {
            get {
                return ((string)(this["EdocsSupport"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LABREQS")]
        public string Archiver {
            get {
                return ((string)(this["Archiver"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SendErrorEmailsOnly {
            get {
                return ((bool)(this["SendErrorEmailsOnly"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AuditLogFolder {
            get {
                return ((bool)(this["AuditLogFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\Archives\\UploadBatchToAzureCloud\\Edocs.Upload.Batches.AzureCloud.exe")]
        public string UploadToSPScriptPath {
            get {
                return ((string)(this["UploadToSPScriptPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4064908968@vtext.com")]
        public string TextTo {
            get {
                return ((string)(this["TextTo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TextCc {
            get {
                return ((string)(this["TextCc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^1\\d{9}$|^1\\d{8}$|^2\\d{8}|^2\\d{9}$")]
        public string ValidCSNNumbers {
            get {
                return ((string)(this["ValidCSNNumbers"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("L:\\Archives\\ManuelIndexingJSFilesCurrent")]
        public string ManuelIndexingJSFilesCurrent {
            get {
                return ((string)(this["ManuelIndexingJSFilesCurrent"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\Archives\\ManuelIndexingJSFilesCurrent\\")]
        public string ManuelIndexingJSBackUp {
            get {
                return ((string)(this["ManuelIndexingJSBackUp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowUploadWindow {
            get {
                return ((bool)(this["ShowUploadWindow"]));
            }
        }
    }
}
